export enum LaboActions {
    /**
     * fetch all labos
     */
    LAB_LABOS_FETCH_ALL = "@@labos/LAB_LABOSFETCH_ALL",
    LAB_LABOS_FETCH_ALL_ERROR = "@@labos/LAB_LABOS_FETCH_ALL_ERROR",
    LAB_LABOS_FETCH_ALL_SUCCESS = "@@labos/LAB_LABOS_FETCH_ALL_SUCCESS",
    /**
     * fetch labos by city
     */
    LAB_LABOS_FETCH_TWENTY_BY_CITY = "@@labos/LAB_LABOSFETCH_TWENTY_BY_CITY",
    LAB_LABOS_FETCH_TWENTY_BY_CITY_ERROR = "@@labos/LAB_LABOS_FETCH_TWENTY_BY_CITY_ERROR",
    LAB_LABOS_FETCH_TWENTY_BY_CITY_SUCCESS = "@@labos/LAB_LABOS_FETCH_TWENTY_BY_CITY_SUCCESS",
    /**
     * fetch labos by city
     */
    LAB_LABOS_FETCH_BY_CITY = "@@labos/LAB_LABOSFETCH_BY_CITY",
    LAB_LABOS_FETCH_BY_CITY_ERROR = "@@labos/LAB_LABOS_FETCH_BY_CITY_ERROR",
    LAB_LABOS_FETCH_BY_CITY_SUCCESS = "@@labos/LAB_LABOS_FETCH_BY_CITY_SUCCESS",

    /**
     * fetch lab details
     */
    LAB_LABO_FETCH_DETAILS = "@@labos/LAB_LABO_FETCH_DETAILS",
    LAB_LABO_FETCH_DETAILS_ERROR = "@@labos/LAB_LABO_FETCH_DETAILS_ERROR",
    LAB_LABO_FETCH_DETAILS_SUCCESS = "@@labos/LAB_LABO_FETCH_DETAILS_SUCCESS",
    /**
     * lab search
     */
    LAB_LABO_SEARCH_BY_NAME = "@@labos/LAB_LABO_SEARCH_BY_NAME",
    LAB_LABO_SEARCH_BY_NAME_ERROR = "@@labos/LAB_LABO_SEARCH_BY_NAME_ERROR",
    LAB_LABO_SEARCH_BY_NAME_SUCCESS = "@@labos/LAB_LABO_SEARCH_BY_NAME_SUCCESS",
}