apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-dev
  labels:
    app: ittyni
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ittyni
  template:
    metadata:
      labels:
        app: ittyni
    spec:
      containers:
      - name: ittyni
        image: khmammed/ittyni:tt_dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tt-dev
  labels:
    app: ittyni
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ittyni