apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt-prod
  labels:
    app: tt-Prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tt-Prod
  template:
    metadata:
      labels:
        app: tt-Prod
    spec:
      containers:
      - name: ittyni
        image: khmammed/ittyni:tt_prod
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tt-prod
  labels:
    app: tt-Prod
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tt-Prod