export enum CCAMActions {
    /**
     * fetch labTests
     */  
    CCAM_LIST_BY_CODE = "@@CCAM/CCAM_LIST_BY_CODE",
    CCAM_LIST_BY_CODE_ERROR = "@@CCAM/CCAM_LIST_BY_CODE_ERROR",
    CCAM_LIST_BY_CODE_SUCCESS = "@@CCAM/CCAM_LIST_BY_CODE_SUCCESS",
    /**
     * fetch labTests
     */  
    CCAM_FETCH_ACTE_DETAILS = "@@CCAM/CCAM_FETCH_ACTE_DETAILS",
    CCAM_FETCH_ACTE_DETAILS_ERROR = "@@CCAM/CCAM_FETCH_ACTE_DETAILS_ERROR",
    CCAM_FETCH_ACTE_DETAILS_SUCCESS = "@@CCAM/CCAM_FETCH_ACTE_DETAILS_SUCCESS",

  }
  